name: Build Kivy APK

on:
  push:
    branches:
      - main  # atau 'master', tergantung nama branch kamu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git zip unzip openjdk-11-jdk \
          python3-pip python3-setuptools python3 python3-dev \
          ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
          libgstreamer1.0-0 libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
          xclip xsel libjpeg-dev

        pip install --upgrade pip
        pip install cython virtualenv
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: bertani-cerdas-apk
        path: bin/*.apk
